[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "YTeva"
authors = [{name = "Dev Eva", email = "dev.eslam205@outlook.com"}]
dynamic = ["version", "description"]
